font:
    normal:
        family: monospace
        style: Regular

    bold:
        family: monospace
        style: Bold

    italic:
        family: monospace
        style: Italic

    bold_italic:
        family: monospace
        style: Bold Italic

    size: 11.5

# Colors (Monokai Dark)
colors:
    # Default colors
    primary:
        background: "#272822"
        foreground: "#F8F8F2"

    # Normal colors
    normal:
        black: "#272822"
        red: "#F92672"
        green: "#A6E22E"
        yellow: "#F4BF75"
        blue: "#66D9EF"
        magenta: "#AE81FF"
        cyan: "#A1EFE4"
        white: "#F8F8F2"

    # Bright colors
    bright:
        black: "#75715E"
        red: "#F92672"
        green: "#A6E22E"
        yellow: "#F4BF75"
        blue: "#66D9EF"
        magenta: "#AE81FF"
        cyan: "#A1EFE4"
        white: "#F9F8F5"
